/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RentalMobil;
import Koneksi.koneksi;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.util.calendar.BaseCalendar;
/**
 *
 * @author Lenovo
 */
public class frmRental extends javax.swing.JFrame {
private Connection con;
private Statement st;
private ResultSet RsRental;
private ResultSet RsMobil;
private ResultSet RsPenyewa;
private String sql="";
    
private String tanggal,idrental,idmobil,idpenyewa,namapenyewa,namamobil,bm,status,statusb;
private int harga;
    /**
     * Creates new form frmRental
     */
    public frmRental() {
        initComponents();
        KoneksiRental();
        TampilData(sql);
    }

    private void KoneksiRental(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_rental_mobil", "root","");
            System.out.println("Koneksi Berhasil");
        } catch (Exception e) {
            System.out.println("Koneksi Gagal \n"+e);
        }
    }
    private void TampilData (String sql){
        DefaultTableModel datalist = new DefaultTableModel();
        datalist.addColumn("No");
        datalist.addColumn("ID RENTAL");
        datalist.addColumn("ID MOBIL");
        datalist.addColumn("ID PENYEWA");
        datalist.addColumn("TANGGAL RENTAL");
        datalist.addColumn("HARGA RENTAL");
        datalist.addColumn("STATUS");
        try {
            int i = 1;
            st=con.createStatement();
            RsRental=st.executeQuery("SELECT * FROM tb_rental") ;
            while (RsRental.next())
                datalist.addRow(new Object[]{
                    (""+i++),
                    RsRental.getString(1), RsRental.getString(2), 
                    RsRental.getString(3), RsRental.getString(6), 
                    RsRental.getString(7), RsRental.getString(8) 
                });
            tabel.setModel(datalist);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                "Gagal Tampil \n"+e.getMessage());
        }
    }
    private void bersih(){
        Txt_bm.setText("");
        Txt_harga.setText("");
        Txt_id_rental.setText("");
        Txt_nama_mobil.setText("");
        Txt_nama_penyewa.setText("");
        Txt_status.setText("");
        Cmb_id_mobil.setSelectedItem("PILIH");
        Cmb_id_penyewa.setSelectedItem("PILIH");
        Cmb_status.setSelectedItem("Pilih");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Txt_id_rental = new javax.swing.JTextField();
        Cmb_status = new javax.swing.JComboBox<>();
        Cmb_id_penyewa = new javax.swing.JComboBox<>();
        Cmb_id_mobil = new javax.swing.JComboBox<>();
        Txt_nama_penyewa = new javax.swing.JTextField();
        Txt_nama_mobil = new javax.swing.JTextField();
        Txt_bm = new javax.swing.JTextField();
        Txt_harga = new javax.swing.JTextField();
        Txt_status = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        BTN_SIMPAN = new javax.swing.JButton();
        BTN_BATAL = new javax.swing.JButton();
        BTN_HAPUS = new javax.swing.JButton();
        BTN_KELUAR = new javax.swing.JButton();
        tanggalrental = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID RENTAL");

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PILIHAN SEWA");

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID PENYEWA");

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID MOBIL");

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NAMA PENYEWA");

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NAMA MOBIL");

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BM MOBIL");

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("HARGA RENTAL");

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TANGGAL");

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("STATUS");

        Txt_id_rental.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_id_rentalKeyPressed(evt);
            }
        });

        Cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "SEWA" }));
        Cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_statusActionPerformed(evt);
            }
        });

        Cmb_id_penyewa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cmb_id_penyewaItemStateChanged(evt);
            }
        });
        Cmb_id_penyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_id_penyewaActionPerformed(evt);
            }
        });

        Cmb_id_mobil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cmb_id_mobilItemStateChanged(evt);
            }
        });
        Cmb_id_mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_id_mobilActionPerformed(evt);
            }
        });

        Txt_nama_penyewa.setEnabled(false);

        Txt_nama_mobil.setEnabled(false);

        Txt_bm.setEnabled(false);

        Txt_harga.setEnabled(false);

        Txt_status.setEnabled(false);
        Txt_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_statusActionPerformed(evt);
            }
        });

        tabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID RENTAL", "ID PENYEWA", "ID MOBIL", "HARAGA RENTAL", "TANGGAL RENTAL", "STATUS"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        BTN_SIMPAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/save-16x16.png"))); // NOI18N
        BTN_SIMPAN.setText("SIMPAN");
        BTN_SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SIMPANActionPerformed(evt);
            }
        });

        BTN_BATAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/save-and-close-16x16.png"))); // NOI18N
        BTN_BATAL.setText("BATAL");
        BTN_BATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BATALActionPerformed(evt);
            }
        });

        BTN_HAPUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/delete-16x16.png"))); // NOI18N
        BTN_HAPUS.setText("HAPUS");
        BTN_HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_HAPUSActionPerformed(evt);
            }
        });

        BTN_KELUAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/close-16x16.png"))); // NOI18N
        BTN_KELUAR.setText("KELUAR");
        BTN_KELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_KELUARActionPerformed(evt);
            }
        });

        tanggalrental.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalrentalPropertyChange(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Monospaced", 3, 40)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Form Rental");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/HOME.png"))); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(BTN_SIMPAN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN_BATAL))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_id_rental, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Cmb_id_penyewa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Cmb_id_mobil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Txt_nama_penyewa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txt_harga, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tanggalrental, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(Txt_status)
                                    .addComponent(Txt_bm)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_nama_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(BTN_HAPUS)
                                .addGap(18, 18, 18)
                                .addComponent(BTN_KELUAR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel11))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_id_rental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Cmb_id_penyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Cmb_id_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Txt_nama_penyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_nama_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Txt_bm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tanggalrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_SIMPAN)
                    .addComponent(BTN_BATAL)
                    .addComponent(BTN_HAPUS)
                    .addComponent(BTN_KELUAR)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tanggalrentalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalrentalPropertyChange
        // TODO add your handling code here:
        if(tanggalrental.getDate()!=null){
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
            tanggal=format.format(tanggalrental.getDate());
        }
    }//GEN-LAST:event_tanggalrentalPropertyChange

    private void BTN_KELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_KELUARActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BTN_KELUARActionPerformed

    private void BTN_HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HAPUSActionPerformed
        // TODO add your handling code here:
        idrental=String.valueOf(Txt_id_rental.getText());
        try {
            sql="delete from tb_rental where id_rental = '"+ idrental +"'";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null, "data berhasil dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dihapus"+e.getMessage());
        }
    }//GEN-LAST:event_BTN_HAPUSActionPerformed

    private void BTN_BATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BATALActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_BTN_BATALActionPerformed

    private void BTN_SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SIMPANActionPerformed
        // TODO add your handling code here:
        idrental=String.valueOf(Txt_id_rental.getText());
        idmobil=Cmb_id_mobil.getItemAt(Cmb_id_mobil.getSelectedIndex()).toString();
        idpenyewa=Cmb_id_penyewa.getItemAt(Cmb_id_penyewa.getSelectedIndex()).toString();
        namapenyewa=String.valueOf(Txt_nama_penyewa.getText());
        namamobil=String.valueOf(Txt_nama_mobil.getText());
        bm=String.valueOf(Txt_bm.getText());
        harga=Integer.parseInt(Txt_harga.getText());
        status=Cmb_status.getItemAt(Cmb_status.getSelectedIndex()).toString();
        if (Cmb_status.getSelectedItem().equals("PILIH")){
            JOptionPane.showMessageDialog(null, "MAAF STATUS BELUM TERPILIH");
        }
        else {
            try {
                sql="INSERT INTO tb_rental(id_rental, id_mobil, "
                + "id_penyewa, nama_penyewa, nama_mobil, "
                + "tgl_rental, harga_rental,status)VALUE"
                + "('"+ idrental +"','"+ idpenyewa +"','"+ idmobil +"','"+ namapenyewa +"',"
                + "'"+ namamobil +"','"+ tanggal +"','"+ harga +"','"+ status +"')";
                st=con.createStatement();
                st.execute(sql);
                bersih();
                TampilData(sql);
                JOptionPane.showMessageDialog(null,
                    "Data Berhasil Disimpan");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                    "Data Gagal Disimpan \n"+e.getMessage());

            }
        }
        //uPDATE DATA STATUS NOTREADY setelah data disewa
        try {
            status = "NOTREADY";
            sql="update tb_mobil set status = '"+ status +"' where id_mobil = '"+ idmobil +"'";
            st=con.createStatement();
            st.execute(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "maaf error"+e.getMessage());
        }

        try {
            String sql="select * from tb_penyewa";
            Statement st = con.createStatement();
            RsPenyewa=st.executeQuery(sql);
            status = "NOTREADY";
            sql="update tb_penyewa set status = '"+ status +"' where id_penyewa = '"+ idpenyewa +"'";
            st=con.createStatement();
            st.execute(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "maaf error"+e.getMessage());
        }
    }//GEN-LAST:event_BTN_SIMPANActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        /*
        try{
            int i = tabel.getSelectedRow();
            String tabel_klik = (tabel.getModel().getValueAt(i, 0).toString());
            Connection con = new koneksi().konek();
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("SELECT * FROM tb_rental WHERE id_rental = '"+tabel_klik+"'");
            if(sql.next()){
                String kode = sql.getString("id_rental"); 
                Txt_id_rental.setText(kode);
                Txt_id_rental.setEditable(false);
                
                String status = sql.getString("status"); 
                Txt_status.setText(status);
                
                //String id_rentalnya = sql.getString("id_rental");
                //Cmb_id_rental.setSelectedItem(id_rentalnya);
                
                String id_penyewanya = sql.getString("id_penyewa");
                Cmb_id_penyewa.setSelectedItem(id_penyewanya);
                
                String id_mobilnya = sql.getString("id_mobil");
                Cmb_id_mobil.setSelectedItem(id_mobilnya);
                
                String penyewanya = sql.getString("nama_penyewa");
                Txt_nama_penyewa.setText(penyewanya);
                
                String nama_mobil = sql.getString("nama_mobil");
                Txt_nama_mobil.setText(nama_mobil);
                
                String bm_mobil = sql.getString("bm_mobil");
                Txt_bm.setText(bm_mobil);
                
                
                
                String harga = sql.getString("harga_rental");
                Txt_harga.setText(harga);
                
                
                /*try{
                    java.sql.Statement sdm = con.createStatement();
                    java.sql.ResultSet sl = sdm.executeQuery("SELECT * FROM tb_mobil WHERE id_mobil = '"+id_mobilnya+"'");
                    if(sl.next()){
                        String bm = sl.getString("bm_mobil");
                        Txt_bm.setText(bm);
                        Txt_bm.setEditable(false);
                    }
                }catch (Exception e){
                }
                
                try{
                    java.sql.Statement sdm = con.createStatement();
                    java.sql.ResultSet sl = sdm.executeQuery("SELECT * FROM tb_penyewa WHERE id_penyewa = '"+id_penyewanya+"'");
                    if(sl.next()){
                        String nama = sl.getString("nama_penyewa");
                        Txt_nama_penyewa.setText(nama);
                        Txt_nama_penyewa.setEditable(false);
                    }
                }catch (Exception e){
                }*/
                
                                
                
                
                //String tanggal_rental = sql.getString("tgl_rental");
                //tanggalrental.setDate(tanggal_rental);
                
            /*}
        }catch(Exception e){
        }*/
        //
    }//GEN-LAST:event_tabelMouseClicked

    private void Txt_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_statusActionPerformed

    private void Cmb_id_mobilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cmb_id_mobilItemStateChanged
        // TODO add your handling code here:
        try {
            sql="select * from tb_mobil where "
            + "id_mobil='"+ Cmb_id_mobil.getSelectedItem() +"'";
            st=con.createStatement();
            RsMobil=st.executeQuery(sql);
            while (RsMobil.next()){
                Txt_nama_mobil.setText(RsMobil.getString("nama_mobil"));
                Txt_bm.setText(RsMobil.getString(4));
                Txt_harga.setText(RsMobil.getString(5));
                Cmb_status.setSelectedItem(RsMobil.getString(6));
            }
            Txt_nama_mobil.requestFocus();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Cmb_id_mobilItemStateChanged

    private void Cmb_id_penyewaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cmb_id_penyewaItemStateChanged
        // TODO add your handling code here:
        try {
            sql="select * from tb_penyewa where "
            + "id_penyewa='"+ Cmb_id_penyewa.getSelectedItem() +"'";
            st=con.createStatement();
            RsPenyewa=st.executeQuery(sql);
            while (RsPenyewa.next()){
                Txt_nama_penyewa.setText(RsPenyewa.getString("nama_penyewa"));
            }
            Txt_nama_penyewa.requestFocus();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Cmb_id_penyewaItemStateChanged

    private void Cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_statusActionPerformed
        // TODO add your handling code here:
//        if (Cmb_status.getSelectedItem()=="SEWA"){
//            status=String.valueOf(Cmb_status.getSelectedItem());
//            statusb=String.valueOf(Txt_status.getText());
//            statusb = "READY";
//            Txt_status.setText(String.valueOf(statusb));
//        }
        statusb = "READY";
        Txt_status.setText(String.valueOf(statusb));
        if (Cmb_status.getSelectedItem()=="SEWA"){
            Cmb_id_mobil.removeAllItems();
            Cmb_id_mobil.addItem("PILIH");
            try {
                status=String.valueOf(Txt_status.getText());
                //status = "READY";
                String Sql = "select * from tb_mobil where status = '"+ status +"'";
                Statement st = con.createStatement();
                RsMobil=st.executeQuery(Sql);
                while (RsMobil.next()){
                    String Aliaskd = RsMobil.getString("id_mobil");
                    Cmb_id_mobil.addItem(Aliaskd);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                    "Gagal Menampilkan id mobil \n"
                    +e.getMessage());
            }
            Cmb_id_penyewa.removeAllItems();
            Cmb_id_penyewa.addItem("Pilih");
            try {
                status=String.valueOf(Txt_status.getText());
                //status = "READY";
                String Sql = "select * from tb_penyewa where status = '"+ status +"'";
                Statement st = con.createStatement();
                RsPenyewa=st.executeQuery(Sql);
                while (RsPenyewa.next()){
                    String Aliaskd = RsPenyewa.getString("id_penyewa");
                    Cmb_id_penyewa.addItem(Aliaskd);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                    "Gagal Menampilkan id mobil \n"
                    +e.getMessage());
            }
        }
    }//GEN-LAST:event_Cmb_statusActionPerformed

    private void Txt_id_rentalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_id_rentalKeyPressed
        // TODO add your handling code here:
        idrental=Txt_id_rental.getText();
        int tekanenter=evt.getKeyCode();
        if (tekanenter==10){
            try {
                Cmb_id_mobil.removeAllItems();
                String Sql = "select * from tb_mobil";
                Statement st = con.createStatement();
                RsMobil=st.executeQuery(Sql);
                while (RsMobil.next()){
                    String AliasID = RsMobil.getString("id_mobil");
                    Cmb_id_mobil.addItem(AliasID);
                    Cmb_status.setEnabled(false);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                    "Gagal Menampilkan id mobil \n"
                    +e.getMessage());
            }
            try {
                Cmb_id_penyewa.removeAllItems();
                String Sql = "select * from tb_penyewa";
                Statement st = con.createStatement();
                RsPenyewa=st.executeQuery(Sql);
                while (RsPenyewa.next()){
                    String Aliaskd = RsPenyewa.getString("id_penyewa");
                    Cmb_id_penyewa.addItem(Aliaskd);
                    Cmb_status.setEnabled(false);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,
                    "Gagal Menampilkan id mobil \n"
                    +e.getMessage());
            }
            try {
                sql="select * from tb_rental "
                + "where id_rental='"+ idrental +"'";
                st=con.createStatement();
                RsRental=st.executeQuery(sql);
                while (RsRental.next()){
                    Cmb_id_mobil.setSelectedItem(RsRental.getString("id_mobil"));
                    Cmb_id_penyewa.setSelectedItem(RsRental.getString("id_penyewa"));
                    Txt_nama_penyewa.setText(RsRental.getString("nama_penyewa"));
                    Txt_nama_mobil.setText(RsRental.getString("nama_mobil"));
                    tanggalrental.setDate(RsRental.getDate("tgl_rental"));
                    Txt_harga.setText(RsRental.getString("harga_rental"));
                    Txt_status.setText(RsRental.getString("status"));
                    JOptionPane.showMessageDialog(null, "Data Ditemukan");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gak Ketemu \n"
                    +e.getMessage());
                Cmb_id_mobil.requestFocus();
            }
        }
    }//GEN-LAST:event_Txt_id_rentalKeyPressed
    
    private void Cmd_id_penyewaItemStateChanged(java.awt.event.ItemEvent evt){
        try{
            sql="select * from tb_penyewa "
                + "where id_penyewa='"+ Cmb_id_penyewa.getSelectedItem() +"'";
            st=con.createStatement();
            RsPenyewa=st.executeQuery(sql);
            while (RsPenyewa.next()){
                   Txt_nama_penyewa.setText(RsPenyewa.getString("nama_penyewa"));
                }
            Txt_nama_penyewa.requestFocus();
        }catch(Exception e){
            
        }
    }
    
     private void Cmd_id_mobilItemStateChanged(java.awt.event.ItemEvent evt){
        try{
            sql="select * from tb_mobil "
                + "where id_mobil='"+ Cmb_id_mobil.getSelectedItem() +"'";
            st=con.createStatement();
            RsMobil=st.executeQuery(sql);
            while (RsPenyewa.next()){
                   Txt_nama_mobil.setText(RsMobil.getString("nama_mobil"));
                   Txt_bm.setText(RsMobil.getString(4));
                   Txt_harga.setText(RsMobil.getString(5));
                   Cmb_status.setSelectedItem(RsMobil.getString(6));
                }
            Txt_nama_mobil.requestFocus();
        }catch(Exception e){
            
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        MENU_UTAMA fm = new MENU_UTAMA();
        fm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Cmb_id_penyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_id_penyewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb_id_penyewaActionPerformed

    private void Cmb_id_mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_id_mobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb_id_mobilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BATAL;
    private javax.swing.JButton BTN_HAPUS;
    private javax.swing.JButton BTN_KELUAR;
    private javax.swing.JButton BTN_SIMPAN;
    private javax.swing.JComboBox<String> Cmb_id_mobil;
    private javax.swing.JComboBox<String> Cmb_id_penyewa;
    private javax.swing.JComboBox<String> Cmb_status;
    private javax.swing.JTextField Txt_bm;
    private javax.swing.JTextField Txt_harga;
    private javax.swing.JTextField Txt_id_rental;
    private javax.swing.JTextField Txt_nama_mobil;
    private javax.swing.JTextField Txt_nama_penyewa;
    private javax.swing.JTextField Txt_status;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private com.toedter.calendar.JDateChooser tanggalrental;
    // End of variables declaration//GEN-END:variables
}
