/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RentalMobil;

/**
 *
 * @author Lenovo
 */
public class MENU_UTAMA extends javax.swing.JFrame {

    /**
     * Creates new form MENU_UTAMA
     */
    public MENU_UTAMA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tambah_Sewa = new javax.swing.JButton();
        Tambah_Penyewa = new javax.swing.JButton();
        Pengembalian = new javax.swing.JButton();
        Tambah_Mobil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setFocusCycleRoot(true);

        Tambah_Sewa.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        Tambah_Sewa.setText("RENTAL");
        Tambah_Sewa.setName("JBRental"); // NOI18N
        Tambah_Sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambah_SewaActionPerformed(evt);
            }
        });

        Tambah_Penyewa.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        Tambah_Penyewa.setText("TAMBAH PENYEWA");
        Tambah_Penyewa.setName("JBPenyewa"); // NOI18N
        Tambah_Penyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambah_PenyewaActionPerformed(evt);
            }
        });

        Pengembalian.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        Pengembalian.setText("PENGEMBALIAN");
        Pengembalian.setName("JBPengembalian"); // NOI18N
        Pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PengembalianActionPerformed(evt);
            }
        });

        Tambah_Mobil.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        Tambah_Mobil.setText("TAMBAH MOBIL");
        Tambah_Mobil.setName("JBMobil"); // NOI18N
        Tambah_Mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tambah_MobilActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/mobil.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Monospaced", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rental Mobil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(Tambah_Mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Tambah_Penyewa)
                        .addGap(18, 18, 18)
                        .addComponent(Tambah_Sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pengembalian)
                    .addComponent(Tambah_Penyewa)
                    .addComponent(Tambah_Mobil)
                    .addComponent(Tambah_Sewa))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tambah_MobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambah_MobilActionPerformed
        // TODO add your handling code here:
        frmMobil m=new frmMobil();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_Tambah_MobilActionPerformed

    private void PengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PengembalianActionPerformed
        // TODO add your handling code here:
        frmPengembalian kembali=new frmPengembalian();
        kembali.setVisible(true);
        dispose();
    }//GEN-LAST:event_PengembalianActionPerformed

    private void Tambah_PenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambah_PenyewaActionPerformed
        // TODO add your handling code here:
        frmPenyewa user=new frmPenyewa();
        user.setVisible(true);
        dispose();
    }//GEN-LAST:event_Tambah_PenyewaActionPerformed

    private void Tambah_SewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tambah_SewaActionPerformed
        // TODO add your handling code here:
        frmRental r=new frmRental();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_Tambah_SewaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU_UTAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU_UTAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU_UTAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU_UTAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU_UTAMA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pengembalian;
    private javax.swing.JButton Tambah_Mobil;
    private javax.swing.JButton Tambah_Penyewa;
    private javax.swing.JButton Tambah_Sewa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
